export const VICTORIAN_SUBJECTS = [
  "Mathematics",
  "Mathematical Methods",
  "Specialist Mathematics",
  "Further Mathematics",
  "English",
  "English Language",
  "Literature",
  "EAL/D English",
  "Physics",
  "Chemistry",
  "Biology",
  "Environmental Science",
  "Psychology",
  "History",
  "Geography",
  "Legal Studies",
  "Politics",
  "Business Management",
  "Accounting",
  "Economics",
  "Computer Science",
  "Software Development",
  "Systems Engineering",
  "Visual Communication Design",
  "Media",
  "Studio Arts",
  "Music Performance",
  "Music Styles",
  "Drama",
  "Dance",
  "Theatre Studies",
  "Physical Education",
  "Health and Human Development",
  "Design and Technology",
  "Mandarin",
  "Japanese",
  "French",
  "Italian",
  "Indonesian",
  "Vietnamese",
  "German",
  "Spanish",
  "Science",
  "Calculus",
  "Statistics",
  "Essay Writing",
  "Study Skills",
] as const;

export type VictorianSubject = (typeof VICTORIAN_SUBJECTS)[number];

export const SUBJECT_AREAS: Record<string, string[]> = {
  "Mathematics": ["Mathematics", "Mathematical Methods", "Specialist Mathematics", "Further Mathematics", "Calculus", "Statistics"],
  "English": ["English", "English Language", "Literature", "EAL/D English", "Essay Writing"],
  "Sciences": ["Physics", "Chemistry", "Biology", "Environmental Science", "Psychology", "Science"],
  "Humanities": ["History", "Geography", "Legal Studies", "Politics"],
  "Business": ["Business Management", "Accounting", "Economics"],
  "Technology": ["Computer Science", "Software Development", "Systems Engineering", "Design and Technology"],
  "Arts": ["Visual Communication Design", "Media", "Studio Arts", "Music Performance", "Music Styles", "Drama", "Dance", "Theatre Studies"],
  "Physical Ed": ["Physical Education", "Health and Human Development"],
  "Languages": ["Mandarin", "Japanese", "French", "Italian", "Indonesian", "Vietnamese", "German", "Spanish"],
  "Other": ["Study Skills"],
};
